version: "3"  
services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./home/custom:/etc/mysql/conf.d
      - ./home/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    restart: always
    networks:
      - rede_owncloud
  owncloud:
    image: owncloud
    restart: always
    ports:
      - 80:80
    volumes:
      - ./apps:/var/www/html/apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro    
    networks:
      - rede_owncloud
networks:
  rede_owncloud:
    driver: bridge
